test: make sure that underlying connection is closed
tarantool/mysql pull request #49
Opened 2020-11-03 15:36 UTC by romanhabibov

Closes #31

2020-11-09 19:42 UTC, LeonidVas requested changes
HI! Thank you for the patch.

I suggest using in title something like:" test: add test for ...".

Add Closes #31 

AFAIU, you save the descriptor, close it and expect the same descriptor will be used for a connection. This is a good hypothesis, but please add a comment to your hypothesis. Also, I'm expecting some links to prove your hypothesis (if possible).
Is this only true for linux or other OS too? Will such test work on MacOS, WSL, WSL2? Maybe run this test on Linux only?

2020-11-09 19:42 UTC, LeonidVas commented on test/mysql.test.lua
> +local function test_underlying_conn_closed(test)
This test is about closing a connection during garbage collection, I think it would be nice to include that in the test name.

2020-11-12 10:37 UTC, romanhabibov commented
> HI! Thank you for the patch.
> 
> I suggest using in title something like:" test: add test for ...".
> 
> Add Closes #31
> 
> AFAIU, you save the descriptor, close it and expect the same descriptor will be used for a connection. This is a good hypothesis, but please add a comment to your hypothesis. Also, I'm expecting some links to prove your hypothesis (if possible).
> Is this only true for linux or other OS too? Will such test work on MacOS, WSL, WSL2? Maybe run this test on Linux only?

I couldn't find any directly obvious proof, but let me try. Basing on the statement, that file descriptors are recycled in ascending order. It means, that if we call `open()` and immediately `close()`, we get the first vacant index for a new resource in the file descriptor table. It is important not to call any procedures between `open()` and `close()` that may affect the file descriptor table. After that, we immediately create connection, which creates a socket. Socket is a resource, which occupies the first vacant index in the file descriptor table.

https://sites.ualberta.ca/dept/chemeng/AIX-43/share/man/info/C/a_doc_lib/aixprggd/genprogc/fdescript.htm

2020-11-13 07:49 UTC, Totktonada commented
> I couldn't find any directly obvious proof <...>

The kernel code:

https://github.com/torvalds/linux/blob/585e5b17b92dead8a3aca4e3c9876fbca5f7e0ba/fs/file.c#L503-L510
https://github.com/torvalds/linux/blob/585e5b17b92dead8a3aca4e3c9876fbca5f7e0ba/fs/file.c#L531-L532

The simplified description of this code:

https://www.win.tue.nl/~aeb/linux/vfs/trail-2.html

Another description:

https://stackoverflow.com/a/33502563/1598057

2020-11-13 07:51 UTC, Totktonada commented on test/mysql.test.lua
> +    if is_linux() then
1. Just `jit.os == 'Linux'` is enough.
2. Let's skip the entire test, not just fcntl.

2020-11-13 07:52 UTC, Totktonada commented on test/mysql.test.lua
> +        test:ok(ffi.C.fcntl(handle, 1) == -1, 'descriptor is closed')
Let's define constant F_GETFD and use it. `1` is not self-descriptive.

2020-11-13 07:53 UTC, Totktonada commented on test/mysql.test.lua
> +        password = password, db = db })
It would be better to don't leak the connection even in the test.

2020-11-13 07:53 UTC, Totktonada commented on test/mysql.test.lua
> +        test:ok(true, 'OS is not linux')
I suggest to use `test:skip()` for skipping a test case.

2020-11-17 07:27 UTC, Totktonada commented on test/mysql.test.lua
> +        password = password, db = db })
Ouch, my bad: it should be closed by gc.

2020-11-17 07:27 UTC, Totktonada commented on test/mysql.test.lua
> +end
Dead code.

2020-11-17 08:33 UTC, LeonidVas commented
> > HI! Thank you for the patch.
> > I suggest using in title something like:" test: add test for ...".
> > Add Closes #31
> > AFAIU, you save the descriptor, close it and expect the same descriptor will be used for a connection. This is a good hypothesis, but please add a comment to your hypothesis. Also, I'm expecting some links to prove your hypothesis (if possible).
> > Is this only true for linux or other OS too? Will such test work on MacOS, WSL, WSL2? Maybe run this test on Linux only?
> 
> I couldn't find any directly obvious proof, but let me try. Basing on the statement, that file descriptors are recycled in ascending order. It means, that if we call `open()` and immediately `close()`, we get the first vacant index for a new resource in the file descriptor table. It is important not to call any procedures between `open()` and `close()` that may affect the file descriptor table. After that, we immediately create connection, which creates a socket. Socket is a resource, which occupies the first vacant index in the file descriptor table.
> 
> https://sites.ualberta.ca/dept/chemeng/AIX-43/share/man/info/C/a_doc_lib/aixprggd/genprogc/fdescript.htm

Alexander found confirmation. Please add this as a comment to your code with describing how the test works.

2020-11-17 09:18 UTC, Totktonada commented on test/mysql.test.lua
> +        test:skip(1, 'wrong OS')
1. Please, [look](https://www.tarantool.io/en/doc/latest/reference/reference_lua/tap/#taptest-skip), which arguments 'skip()` accept.
2. I found 'wrong OS' wording a bit offensive. How about just 'non-Linux OS'?
3. While we're here: I would lower indentation level for the testing code this way:

```lua
test:plan(1)
if jit.os ~= 'Linux' then
    -- A comment that explains why it is skipped.
    test:skip('non-Linux OS')
    return
end
<..the test code..>
```

2020-11-17 17:50 UTC, romanhabibov commented on test/mysql.test.lua
> +end
Dropped.

2020-11-17 17:50 UTC, romanhabibov commented
> > > HI! Thank you for the patch.
> > > I suggest using in title something like:" test: add test for ...".
> > > Add Closes #31
> > > AFAIU, you save the descriptor, close it and expect the same descriptor will be used for a connection. This is a good hypothesis, but please add a comment to your hypothesis. Also, I'm expecting some links to prove your hypothesis (if possible).
> > > Is this only true for linux or other OS too? Will such test work on MacOS, WSL, WSL2? Maybe run this test on Linux only?
> > 
> > 
> > I couldn't find any directly obvious proof, but let me try. Basing on the statement, that file descriptors are recycled in ascending order. It means, that if we call `open()` and immediately `close()`, we get the first vacant index for a new resource in the file descriptor table. It is important not to call any procedures between `open()` and `close()` that may affect the file descriptor table. After that, we immediately create connection, which creates a socket. Socket is a resource, which occupies the first vacant index in the file descriptor table.
> > https://sites.ualberta.ca/dept/chemeng/AIX-43/share/man/info/C/a_doc_lib/aixprggd/genprogc/fdescript.htm
> 
> Alexander found confirmation. Please add this as a comment to your code with describing how the test works.

Done.

2020-11-17 17:51 UTC, romanhabibov commented on test/mysql.test.lua
> +        test:skip(1, 'wrong OS')
Done.

2020-11-18 07:51 UTC, LeonidVas commented on test/mysql.test.lua
> +    if fh == nil then error(err) end
To throw the "err", it must exist. I think it should be:
```
local fh, err = fio.open('/dev/zero', {'O_RDONLY'})
```

2020-11-19 00:15 UTC, LeonidVas approved these changes
LGTM.

2020-11-19 07:10 UTC, Totktonada approved these changes
LGTM.

2020-11-19 08:19 UTC, merged