Fiber
tarantool/mysql pull request #55
Opened 2020-12-17 04:46 UTC by romanhabibov

2020-12-22 21:59 UTC, LeonidVas requested changes
Hi! Thank you for the patch.
I don't understand, why you choose `api` as subsystem? You don't change API in the patch.
Please add a detailed description of the situation that could lead to infinite blocking instead of "case in tests".
See some comments below.

2020-12-22 21:59 UTC, LeonidVas commented on mysql/init.lua
>  end
Seems like it can be changed to something like:
```
    local result = (conn.queue:get() and mysqlconn) or POOL_EMPTY_SLOT
    conn.usable = false
    conn.queue:put(false)
    return result
```
and then you wouldn't be using WET technique.
What do you think?

2020-12-22 21:59 UTC, LeonidVas commented on mysql/init.lua
> +                    error('Connection is not usable')
Seems like we must do `self.queue:put(false)` here.
We also had a discussion about why such checks are needed here, and it would be nice to leave a comment on this.

2020-12-22 21:59 UTC, LeonidVas commented on test/mysql.test.lua
> +end
Move "test_block_fiber2" and "fiber_2" inside "test_block_fiber_inf". You can write this function just inside `fiber.create`.

2020-12-22 21:59 UTC, LeonidVas commented on test/mysql.test.lua
> +local fiber_2
You don't have "fiber_1", but have "fiber_2". I can propose to you something like: "fiber_blocked". Maybe you make up a clearer name.

2020-12-22 21:59 UTC, LeonidVas commented on test/mysql.test.lua
> +local function test_block_fiber2(conn)
What for  do you need the "2" in the name of the function?

2020-12-22 21:59 UTC, LeonidVas commented on test/mysql.test.lua
> +    while fiber.status(fiber_2) ~= 'dead' do
Will this test hung in case of failure? If it's true, that's not cool.

2020-12-22 21:59 UTC, LeonidVas commented on test/mysql.test.lua
> +    test:plan(1)
I think it would be nice to add a detailed description:"what is this test about(with link to GH ticket)?".

2020-12-22 21:59 UTC, LeonidVas commented on test/mysql.test.lua
> +     -- Third.
Seems like you count lines:
First
Second
Third

2020-12-22 21:59 UTC, LeonidVas commented on test/mysql.test.lua
> +    local conn, err = mysql.connect({ host = host, port = port, user = user,
AFAIU the global `conn` is already created for tests, why are you creating yet another `conn`? 
Can you use a connection from the pool?

2020-12-22 22:01 UTC, LeonidVas requested changes
Why did you move the second test into a separate commit?

2020-12-22 22:03 UTC, LeonidVas commented
Please, add @ChangeLog for the patchset.

2020-12-22 22:48 UTC, LeonidVas commented
Please give your branch a descriptive name according to SOP(for the future).

2020-12-23 15:10 UTC, romanhabibov commented on mysql/init.lua
>  end
Done.

2020-12-24 09:44 UTC, romanhabibov commented
> Please, add @ChangeLog for the patchset.

Done.

2020-12-24 09:47 UTC, romanhabibov commented
> Please give your branches a descriptive name according to SOP(for the future).

Ok.
I thought this naming was in order not to get confused in the branches, if there are a lot of them. And this repository is not very rich in branches.

2020-12-24 09:50 UTC, romanhabibov commented
> Why did you move the second test into a separate commit?

Because this test is not about pool connections, but my first patch is about. Also, this test does not fail on master, it was added, because Sanya (@Totktonada) requested it in the issue description.

2020-12-24 09:51 UTC, romanhabibov commented on test/mysql.test.lua
> +    local conn, err = mysql.connect({ host = host, port = port, user = user,
Done.

2020-12-24 09:51 UTC, romanhabibov commented on test/mysql.test.lua
> +     -- Third.
Rephrased.

2020-12-24 09:51 UTC, romanhabibov commented on test/mysql.test.lua
> +    test:plan(1)
Done.

2020-12-24 09:52 UTC, romanhabibov commented on test/mysql.test.lua
> +    while fiber.status(fiber_2) ~= 'dead' do
Yes, check my new approach

2020-12-24 09:52 UTC, romanhabibov commented on test/mysql.test.lua
> +local function test_block_fiber2(conn)
Renamed.

2020-12-24 09:52 UTC, romanhabibov commented on test/mysql.test.lua
> +local fiber_2
Renamed.

2020-12-24 09:55 UTC, romanhabibov commented on test/mysql.test.lua
> +end
Done.

2020-12-24 09:55 UTC, romanhabibov commented on mysql/init.lua
> +                    error('Connection is not usable')
Yes, added with comment.

2020-12-24 17:03 UTC, LeonidVas requested changes
Hi! This iteration looks better than the previous one.
See some comments below.

2020-12-24 17:03 UTC, LeonidVas commented on test/mysql.test.lua
> +        local limit = 10000
OMG! Just use timeout like [here](https://lists.tarantool.org/pipermail/tarantool-patches/2020-December/021384.html).

2020-12-24 17:20 UTC, LeonidVas requested changes

2020-12-24 17:20 UTC, LeonidVas commented on test/mysql.test.lua
> +    fiber.create(conn.execute, conn, 'SELECT sleep(0.01)')
I'll be honest with you. I consider this test unnecessary.
But if you want to do it:
- use `Follow-up` instead `Part of`, because it is applied after `Closes`
- think about an easier way to reproduce than using 3 queries with `sleep()`

2020-12-24 17:28 UTC, LeonidVas commented
> > Please, add @ChangeLog for the patchset.
> 
> Done.

Optional!!!
When the user reads the release notes it will be nice if he understand: how the behavior has been changed. Try to write more detailed description.

2020-12-27 18:00 UTC, romanhabibov commented on test/mysql.test.lua
> +    fiber.create(conn.execute, conn, 'SELECT sleep(0.01)')
> I'll be honest with you. I consider this test unnecessary.
> But if you want to do it:
> 
> * use `Follow-up` instead `Part of`, because it is applied after `Closes`

Dropped
> * think about an easier way to reproduce than using 3 queries with `sleep()`

Done.

2020-12-27 18:01 UTC, romanhabibov commented on test/mysql.test.lua
> +        local limit = 10000
Done.

2020-12-27 18:01 UTC, romanhabibov commented on test/mysql.test.lua
> +            conn:execute('SELECT sleep(0.01)')
Done.

2020-12-27 18:01 UTC, romanhabibov commented on test/mysql.test.lua
> +    local function test_fiber_block_long_request(conn)
Done.

2020-12-27 18:02 UTC, romanhabibov commented on test/mysql.test.lua
> +    local c = pool:get()
Renamed.

2020-12-27 18:02 UTC, romanhabibov commented on test/mysql.test.lua
> +local function test_block_fiber_inf(test, pool, conn)
Fixed.

2020-12-27 18:02 UTC, romanhabibov commented on test/mysql.test.lua
> +-- gh-34: Check that fiber is not blocked in the following case. A
Done.

2020-12-27 18:07 UTC, romanhabibov commented on mysql/init.lua
> +                if not self.usable then
Done.

2020-12-27 18:07 UTC, romanhabibov commented on mysql/init.lua
>                  self.queue:put(false)
Done.

2021-01-12 13:04 UTC, LeonidVas requested changes

2021-01-12 13:04 UTC, LeonidVas commented on test/mysql.test.lua
> +    local timeout = 1
WTF? How this "timeout" work?

2021-01-12 13:04 UTC, LeonidVas commented on test/mysql.test.lua
> +    fiber.create(test_fiber_block_request, conn)
I think this is equivalent to `fiber.create(conn.execute, conn, 'SELECT "a"')`. And now we can remove the `test_fiber_block_request` function.

2021-01-12 13:07 UTC, LeonidVas commented
Rebase the branch on master and the CI became green.

2021-01-12 23:20 UTC, romanhabibov commented on test/mysql.test.lua
> +    local timeout = 1
Dropped.

2021-01-12 23:20 UTC, romanhabibov commented on test/mysql.test.lua
> +        fiber_blocked = fiber.self()
Dropped.

2021-01-12 23:21 UTC, romanhabibov commented on test/mysql.test.lua
> +local function test_block_fiber_inf(test, pool)
Now, I check the error message.

2021-01-12 23:35 UTC, romanhabibov commented on test/mysql.test.lua
> +    fiber.create(test_fiber_block_request, conn)
Now, I can't. See the new version.

2021-01-13 20:44 UTC, LeonidVas requested changes
Hi! As for me now the test seems not bad. I think the result could be something like this:
```
--- gh-34: Check that fiber is not blocked in the following case.
-- A connection conn is acquired from a pool and we acquire a
-- lock. Then we start the first fiber with pool:put(conn)`, which
-- try to acquire lock and yield. Then the second fiber is started
-- to perform request with `conn:execute()` which try to acquire
-- lock, because the connection is still marked as `usable` and
-- yield too. It's appeared that the lock is never released. Now,
-- it's fixed.
local function test_block_fiber_inf(test, pool)
    test:plan(2)
    local conn = pool:get()

    local function fiber_block_request(conn)
        local res, err = pcall(conn.execute, conn, 'SELECT "a"')
        test:ok(res == false and string.find(err, 'Connection is broken'),
            'query failed')
    end

    conn.queue:get()
    fiber.create(pool.put, pool, conn)
    local blocked_fiber = fiber.create(fiber_block_request, conn)
    conn.queue:put(true)

    local start_time = fiber.time()
    local timeout = 5
    local is_alive = true

    -- Wait for the blocked fiber to finish,
    -- but no more than "timeout" seconds.
    while fiber.time() - start_time < timeout and is_alive do
        fiber.sleep(0.1)
        is_alive = blocked_fiber:status() ~= 'dead'
    end

    test:ok(is_alive == false, 'fiber is not blocked')
end
```
See some comments below.

2021-01-13 20:44 UTC, LeonidVas commented on test/mysql.test.lua
> +        local res, err = pcall(conn.execute, conn, 'SELECT "a"')
Variable `res` is not used. For such purpose use `_` instead.
Seems like you can use only the `errmsg` and remove the `err` variable.

2021-01-13 20:44 UTC, LeonidVas commented on test/mysql.test.lua
> +            string.find(errmsg, 'Connection is broken') ~= nil,
Indentation.
As I understand from the links on https://www.tarantool.io/en/doc/latest/dev_guide/lua_style_guide/, in this case, you must use one / two "tabs" (4 spaces). Usually one "tab" (4 spaces) is used.

2021-01-13 20:44 UTC, LeonidVas commented on test/mysql.test.lua
> +    fiber.yield()
You don't have any documented guarantee that the blocked fiber will be run before returning to this fiber. I think the true way is to use "timeout" and "sleep".

2021-01-13 20:48 UTC, LeonidVas commented on test/mysql.test.lua
> +    local function test_fiber_block_request(conn)
No big deal, but it looks like the "test" prefix is not needed for the nested function.

2021-01-13 21:31 UTC, romanhabibov commented
> Hi! As for me now the test seems not bad. I think the result could be something like this:
> 
> ```
> --- gh-34: Check that fiber is not blocked in the following case.
> -- A connection conn is acquired from a pool and we acquire a
> -- lock. Then we start the first fiber with pool:put(conn)`, which
> -- try to acquire lock and yield. Then the second fiber is started
> -- to perform request with `conn:execute()` which try to acquire
> -- lock, because the connection is still marked as `usable` and
> -- yield too. It's appeared that the lock is never released. Now,
> -- it's fixed.
> local function test_block_fiber_inf(test, pool)
>     test:plan(2)
>     local conn = pool:get()
> 
>     local function fiber_block_request(conn)
>         local res, err = pcall(conn.execute, conn, 'SELECT "a"')
>         test:ok(res == false and string.find(err, 'Connection is broken'),
>             'query failed')
>     end
> 
>     conn.queue:get()
>     fiber.create(pool.put, pool, conn)
>     local blocked_fiber = fiber.create(fiber_block_request, conn)
>     conn.queue:put(true)
> 
>     local start_time = fiber.time()
>     local timeout = 5
>     local is_alive = true
> 
>     -- Wait for the blocked fiber to finish,
>     -- but no more than "timeout" seconds.
>     while fiber.time() - start_time < timeout and is_alive do
>         fiber.sleep(0.1)
>         is_alive = blocked_fiber:status() ~= 'dead'
>     end
> 
>     test:ok(is_alive == false, 'fiber is not blocked')
> end
> ```
> 
> See some comments below.

I'm okay with your test version. I used it.

2021-01-14 08:18 UTC, LeonidVas approved these changes
LGTM.

2021-01-14 14:53 UTC, Totktonada commented on mysql/init.lua
> +            end
Should not we do the same in `close()`, `reset()` and `quote()`?

If so, let's introduce a helper function.

2021-01-14 14:56 UTC, Totktonada commented on mysql/init.lua
> +            end
Regarding `close()`: let's decide first, whether it should be idempotent.

2021-01-14 15:05 UTC, Totktonada commented on mysql/init.lua
> +            end
We should perform the check even if we got a broken connection (under the upward `if`), because 'broken' connection (one that sees a connectivity problem) is not the same as 'unusable' (closed one). Now the error is misleading.

2021-02-01 04:00 UTC, romanhabibov commented on mysql/init.lua
> +            end
Fixed, if I understood you correctly.

2021-02-01 04:01 UTC, romanhabibov commented on mysql/init.lua
> +            end
IMO, it shouldn't be idempotent. What's the reason? We should throw error if it is already closed.

2021-02-01 04:02 UTC, romanhabibov commented on mysql/init.lua
> +            end
> Should not we do the same in `close()`, `reset()` and `quote()`?
> 
> If so, let's introduce a helper function.

Done.

2021-02-25 19:08 UTC, Totktonada commented on mysql/init.lua
> +        print('aaa')
Forgotten debug.

2021-02-25 19:18 UTC, Totktonada commented on mysql/init.lua
> +local function check_usable_or_broken(conn)
The name is strange. Usable or broken?

Can we name it like `conn_acquire_lock()`?

2021-02-25 19:34 UTC, Totktonada commented on mysql/init.lua
> +            end
Idempotence of `:close()` is the nice property. Let's assume `:close()` may raise an error. A caller should catch it so. But what to do in the case of the error? Just ignore? A bit more boilerplate code.

At least java.sql.Connection objects [have](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#close--) idempotent `.close()`.

However okay: `:close()` is not idempotent now. We can postpone this question.

2021-02-25 19:34 UTC, Totktonada commented on mysql/init.lua
> +            end
Regarding the change itself: looks okay (aside naming, see below).

2021-02-25 19:37 UTC, Totktonada commented on mysql/init.lua
> +            end
Now if the connection is broken and unusable we report that it is unusable. This looks good.

2021-02-25 19:39 UTC, Totktonada commented
I have no objections aside of naming and the forgotten print. I looked at the code and didn't look at the test again (I did it the past time).

Please, rebase the patch upward master.

That's all. I think we can push after that.

2021-02-26 09:45 UTC, romanhabibov commented on mysql/init.lua
> +local function check_usable_or_broken(conn)
Renamed.

2021-02-26 09:45 UTC, romanhabibov commented on mysql/init.lua
> +        print('aaa')
Removed.

2021-02-26 18:10 UTC, romanhabibov commented
Rebased. Let's push?

2021-02-26 18:53 UTC, Totktonada commented
Waiting for PR #58 to run tests.

2021-03-02 16:03 UTC, Totktonada commented
Rebase on top of the latest master.

2021-03-02 21:10 UTC, Totktonada approved these changes

2021-03-02 21:16 UTC, merged