Publish with CI
tarantool/mysql pull request #69
Opened 2022-09-09 10:42 UTC by DifferentialOrange

Use standard rockspec layout. Publish scm-1 rockspec with CI on push to master. Create and publish
tagged rockspecs on tag push.

Remove Travis CI build status badge, set Github Actions fast-testing and publish badge.

2022-09-12 16:31 UTC, LeonidVas requested changes
Hi! Thank you for the patchset.
`ci: publish rockspecs` -> `cd: publish rockspecs`
See several comments bellow.

2022-09-12 16:31 UTC, LeonidVas commented on .github/workflows/publish.yml
> +      - uses: actions/checkout@v2
`actions/checkout@v3`

2022-09-12 16:31 UTC, LeonidVas commented on .github/workflows/publish.yml
> +      - uses: actions/checkout@v2
`actions/checkout@v3`

2022-09-12 16:31 UTC, LeonidVas commented on .github/workflows/publish.yml
> +      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
I remember that @Totktonada  didn't like such method and advised to use https://github.com/tarantool/queue/blob/e56023dc80d77b369cdccb135146fd1f34e770de/.github/workflows/publish.yml#L25 (I don't remember the details). I would suggest comparing the results and making a decision.

2022-09-13 10:44 UTC, DifferentialOrange commented on .github/workflows/publish.yml
> +      - uses: actions/checkout@v2
Used v3 in existing and new pipelines

2022-09-13 10:44 UTC, DifferentialOrange commented on .github/workflows/publish.yml
> +      - uses: actions/checkout@v2
Used v3 in existing and new pipelines

2022-09-13 10:44 UTC, DifferentialOrange commented on .github/workflows/publish.yml
> +      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
Manually sed-ed version is actually the same as scm-1 with replaced `"version"` and `"tag"`, as expected.

`new_version` template is actually a bit weird: it uses three spaces for indentation. And it loses all additions like `--vim` directive comment. And it maybe won't be compatible with non-cmake rockspecs. Let's stick to the queue version.

2022-09-13 12:27 UTC, LeonidVas approved these changes
LGTM

2022-09-13 12:27 UTC, merged